# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c47c874a2325f81ed7a1ef9cc4857461242d54a15cdf9285d5f91e90595471515b63a802ca15c7108f919529a85a7e99bf35e3fd1c15a325770ce2b43a7a1906

test:
  secret_key_base: 696f1d94cb371c4b369d8503d82185bbb83cabace18b0f7f98bd89f7fdba3fd03b8f919f27a162eac6fea1d0ef561411dfd94a264340846a01cfe36969e98e9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
